### ISSUE TITLE
Feature Request: The possibility to change the text of the items for "Available actions" into icons.

### ISSUE THREAD

**Issue by HunterX86** [nielsfaber/alarmo-card#10]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
The possibility to change the button text of the items for "Available actions" into icons.

![Schermafbeelding 2021-11-01 1856062](https://user-images.githubusercontent.com/1310016/139726302-af936482-94ec-44f2-9795-2484edd0ee6f.png)

### Additional info
You can choose to use text or only an icon

![Schermafbeelding 2021-11-01 193740](https://user-images.githubusercontent.com/1310016/139725953-4f4f4b47-63a5-472e-b900-1fc73a0af329.png)

Because i only want to use an icon instead of text.

**Comment by nielsfaber** [comment]
I tried implementing this, but I don't really like the result:
![image](https://user-images.githubusercontent.com/16861605/144242382-3ec5da39-67a6-450d-b94e-2d304592ac7f.png)

In my opinion, the buttons are not really suitable for displaying an icon.
Hence I cannot implement your request.

**Comment by HunterX86** [comment]
And if you increase the scaliing factor to 1.3
Then the buttons looks like a square

**Comment by KameDomotics** [comment]
> I tried implementing this, but I don't really like the result: ![image](https://user-images.githubusercontent.com/16861605/144242382-3ec5da39-67a6-450d-b94e-2d304592ac7f.png)
> 
> In my opinion, the buttons are not really suitable for displaying an icon. Hence I cannot implement your request.

I find it a good result.  can you implement it in the next updates?
Thanks!
