### ISSUE TITLE
Show devices blocking arming by their Alarmo name

### ISSUE THREAD

**Issue by dsgepers** [nielsfaber/alarmo-card#13]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Devices blocking arming should be shown by their Alarmo name instead of the corresponding entity name. (Just like how Notifications work in Alarmo)

### Additional info
Currently the popup showing the devices blocking arming are shown by their entity name, not their (renamed) Alarmo name.

**Comment by nielsfaber** [comment]
I am actually thinking about removing the option to overwrite sensor names in Alarmo.
In my opinion the option is a bit superfluous on top of the "friendly name" setting in HA.
Its also not that easy to have the card communicate with Alarmo to get the sensor name setting.

Perhaps I can create an option to easily overwrite the HA friendly name through Alarmo as an alternative, but that is currently not in place.

What was your reason for overwriting the names of sensors in Alarmo, if I may ask?

**Comment by dsgepers** [comment]
I won't pretend to know everything in HA yet. But I kind of liked custom names, because it means I can use the "friendly HA name" in a more structured way and have the Alarmo name as a way to customize the name in notifications in a more friendly way. 

Also considering I'm coming from a programming background and am a non native english speaker, I like having my "programming" in english, whilst notification names would be in Dutch.

This is all preference, and I can see wanting to drop the custom names as it's effectivly the same thing as what home assistant offers.

**Comment by nielsfaber** [comment]
As I said before, this feature will not be implemented.
If you update to latest version of Alarmo you will see a warning that the sensor name option will be removed.
You can still assign a Dutch name to a sensor and give it an English ID, but it has to be done outside of Alarmo.
I think this is the way forward, I hope you agree.
