### ISSUE TITLE
Keypad not shown in HA Companion App

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo-card#14]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
Keypad is shown when armed and needed when option 'Keep the keypad always visible, also when no code input is required.' is inactive.

### Actual behavior
Since version 1.2.0 the keypad in the HA Companion App (Android) is not shown, when Alarmo is armed and a pincode is needed.
It only appears, when option 'Keep the keypad always visible, also when no code input is required.' is activated. 
It works like expected when using a webbrowser like Chrome and Firefox.

### Steps to Reproduce
- Install official HA Companion App (Android)
- Login to HA
- Configure Alarmo to require a pincode to disarm
- Disable card setting 'Keep the keypad always visible, also when no code input is required.'
- Arm Alarmo
- Try to disarm using the card in the HA Companion App

![Screenshot_20211128-180335_Home Assistant](https://user-images.githubusercontent.com/88980079/143778600-c7517f53-d7a7-4981-9b6d-3f9051d1e703.jpg)

**Comment by StevenBoelhouwer** [comment]
I have the "Keep the keypad always visible, also when no code input is required." active and I'm not seeing the keypad "always". It only shows when an alarm is armed. That would be your intended way of working so it look likes its working is a bit mixed up.

**Comment by pepe59** [comment]
Same here.

**Comment by nielsfaber** [comment]
I can confirm this issue:
> I have the "Keep the keypad always visible, also when no code input is required." active and I'm not seeing the keypad "always".

I overlooked this case when I was testing it. I have to make some more changes to cover this function.

Otherwise the issue is not really clear to me. For me all works as I would expect it. 
Is the issue specific to the companion app? 
If so, it’s likely a matter of caching, so you are still seeing the old card.

**Comment by pepe59** [comment]
Here I have this problem on all devices: Chrome browser on PC, Android tablet and phone with companion application.
I've tried clearing the cache and that doesn't help.

**Comment by StevenBoelhouwer** [comment]
> I can confirm this issue:
> 
> > I have the "Keep the keypad always visible, also when no code input is required." active and I'm not seeing the keypad "always".
> 
> I overlooked this case when I was testing it. I have to make some more changes to cover this function.
> 
> Otherwise the issue is not really clear to me. For me all works as I would expect it. Is the issue specific to the companion app? If so, it’s likely a matter of caching, so you are still seeing the old card.

Let me know if you need help testing!

**Comment by nielsfaber** [comment]
Please update the card to v1.2.1. This version should have the problem fixed.
