### ISSUE TITLE
Setting for hiding sensors blocking alarm activation

### ISSUE THREAD

**Issue by chrispazz** [nielsfaber/alarmo-card#15]
Using Alarmo with small tablets (ex. Fire HD), when some sensor is blocking alarm activation, they pop-up above the alarmo  panel lowering it (and getting it outside of the screen if it is big enough to be usable on such tablets).

Is it possible to have a configuration option to disable this (I show sensors by myself with custom buttons in another card) or a configuration to hide icon and showing only the name of the sensor (so that less space is wasted)?

Thank you

**Comment by nielsfaber** [comment]
I have added this option to the card config (also possible to set in yaml mode using `show_messages`):
![image](https://user-images.githubusercontent.com/16861605/144247220-5d15fbbe-11b2-488c-b60e-75fa0c5bd814.png)
If you turn this off the messages will be suppressed.

Showing only sensor names seemed a bit of a bad compromise to me, I didn't know how to make it look OK still.

**Comment by nielsfaber** [comment]
You can update the card to v1.2.1 to see the new option.
Please close the issue if the added function satisfies your needs.

**Comment by chrispazz** [comment]
Perfect!
Thank you!
C
