### ISSUE TITLE
Red line over text when alarm triggered

### ISSUE THREAD

**Issue by h3nrytan** [nielsfaber/alarmo-card#17]
![{DB0F7598-178A-45D7-9D71-BE865CEAFE68}](https://user-images.githubusercontent.com/3590384/144365557-f66a7d84-9557-4512-a449-4442b865628b.png)

Hello!

Attached for you to preview. Red line over text.

Thanks.

**Comment by nielsfaber** [comment]
In which browser do you see this?

**Comment by h3nrytan** [comment]
I see this on Google Chrome and Samsung Tab A7

**Comment by nielsfaber** [comment]
This should be resolved in v1.2.2. Please test it and close the issue if so, otherwise let me know.

**Comment by h3nrytan** [comment]
tested on my chrome browser and samsung tablet with fully kiosk browser. all good! thank you for the fix!
