### ISSUE TITLE
Button color text to hard to see in dark mode.

### ISSUE THREAD

**Issue by HunterX86** [nielsfaber/alarmo-card#18]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
Bring back the old button collor text in dark mode templates.
I prefer white color text in dark mode.

### Actual behavior
![keypad](https://user-images.githubusercontent.com/1310016/145099802-331e7123-64d6-4c77-869c-961c8d45dec9.png)
default dark mode

![keypad custom template](https://user-images.githubusercontent.com/1310016/145099820-3a0924a1-dc43-46c5-ba1f-5f98ef5c328a.png)
custom theme

### Steps to Reproduce
To reproduce change theme to dark or a custom theme.

**Comment by nielsfaber** [comment]
I think you are looking at disabled buttons, which are supposed to be greyed out.

In the dark mode I would expect it to look like this:
![image](https://user-images.githubusercontent.com/16861605/146667258-7a091b84-1b28-41ba-a1f3-f6503b5b703d.png)

On the right you see the official HA Alarm Panel card, there is no difference in readability.

**Comment by HunterX86** [comment]
ok i didn't know that. Sorry for the question.
