### ISSUE TITLE
Countdown Timer

### ISSUE THREAD

**Issue by h3nrytan** [nielsfaber/alarmo-card#19]
The countdown timer starts from the beginning when i close/reopen pop up or i refresh the browser.

Possible to have a persistent timer?

**Comment by nielsfaber** [comment]
This should be resolved in v1.2.2. Please test it and close the issue if so, otherwise let me know.

**Comment by h3nrytan** [comment]
tested on my chrome browser and samsung tablet with fully kiosk browser. all good! thank you for the fix!
