### ISSUE TITLE
Icon colour changes to help colour blindness

### ISSUE THREAD

**Issue by moorep999** [nielsfaber/alarmo-card#2]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Allow the background colour to be changed by the user, or a more colour blind friendly colour scheme chosen. 

### Additional info
Like around 10% of the population, I'm red/green colour-blind. This means I can't actually distinguish between the armed and disarmed icons easily (or at all in some light). If user chosen colour scheme wouldn't be possible, then a (hopefully) simple change to say blue for disarmed and red for armed would make it extremely clear. I realise this is this sounds trivial, however the difference between red and blue to me, is the same as the difference between red and green to you and the other 90%.

**Comment by nielsfaber** [comment]
The colours of the icon are not chosen by me actually, it is the same as the Alarm Panel card (except for disarmed, I chose neutral blue instead of green).

The icon + text below should be more descriptive than the icon colour.
So I’m not sure whether this change is needed (but obviously I cannot see it through your eyes).

Perhaps I can make it customisable. I would have to check.

**Comment by nielsfaber** [comment]
Alarmo-card uses the colors `label-badge-green`, and `label-badge-red`.
Green is for disarmed, red is for armed and triggered.
They are defined within HA (see [here](https://github.com/home-assistant/frontend/blob/dev/src/resources/ha-style.ts#L53)), but you can overwrite them using themes.
I suggest you make use of theming to make the colors appear such that they are clear to you.
I am not planning to make the colors configurable from the card, this is not inline with other HA cards.

**Comment by moorep999** [comment]
Thanks, I’ll have a look
