### ISSUE TITLE
circles around the icon are not aligned when changing browser zoom in safari.

### ISSUE THREAD

**Issue by jtonk** [nielsfaber/alarmo-card#20]
### Checklist
- [ x] I checked for similar existing issues (both open and closed) before posting.
- [ x] I am running the latest version.

### Expected behavior
card to properly scale when browser zoom is adjusted when using safari

### Actual behavior
circles around the icon are not aligned

### Steps to Reproduce
change the browser zoom level in safari macOS Monterey 12.0.1, see picture
<img width="355" alt="Screenshot 2021-12-15 at 20 30 05" src="https://user-images.githubusercontent.com/731526/146259351-c1969c89-2f2c-4ffe-abfa-4a3c658b8960.png">

--- UPDATE ---
I think I found the culprit: the `.remaining` class has a `transfer:rotate(90deg)`. if removed or set to 0 it aligns with the white circle

**Comment by nielsfaber** [comment]
This should be resolved in v1.2.2. Please test it and close the issue if so, otherwise let me know.

**Comment by jtonk** [comment]
tnx! ik looks good now in safari as well.

**Comment by Misiu** [comment]
@jtonk please close the issue if everything works as expected

**Comment by nielsfaber** [comment]
@Misiu you here 👀? I didn’t know you were secretly using alarmo 😉

**Comment by Misiu** [comment]
@nielsfaber not yet :) I browse useful repositories from time to time, and I saw one issue that could be closed :)
I'm installing motion sensors and door sensors in my new house, so give me some time and I'll definitively use alarmo 💪
