### ISSUE TITLE
Alarmo Card does not reflect Alarmo state if Alarmo state is set via MQTT

### ISSUE THREAD

**Issue by swests** [nielsfaber/alarmo-card#21]
### Checklist
- [ X I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
Node Red User:  I use Alexa in to arm alarm, that pushed the state change to MQTT...
When I send "arming" via MQTT to alarmo/state, I would expect the Alarmo Card to update to arming, show keypad, etc.

### Actual behavior
When I put the state change to MQTT, the Alarmo Card stays on it's "disarmed" iew

### Steps to Reproduce
Push "arming" to MQTT:alarmo/state

**Comment by nielsfaber** [comment]
Alarmo **state** topic is output only. You cannot force a state change with it. You need to use the **command** topic to arm/disarm instead.
Please read the [docs](https://github.com/nielsfaber/alarmo#state-topic) before declaring a bug.
I'm closing this since I consider it a false report.

**Comment by swests** [comment]
Sincere apologies - missed the "output topic".

**Comment by nielsfaber** [comment]
No worries, hope your issue is solved now.
