### ISSUE TITLE
Different scaling options for Arm buttons and keypad

### ISSUE THREAD

**Issue by swests** [nielsfaber/alarmo-card#22]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I use the card on a Fire 7 in landscape mode.  Would be great to have some more formatting options, e.g. bigger ARM buttons, spacing above the button, etc. and have these separate to scaling for the keypad.

### Additional info
Pure visual enhancements

**Comment by swests** [comment]
I was thinking about this and perhaps just two scale sliders - one for the disarmed actions screen, and another for the keypad screen would be great.

**Comment by swests** [comment]
Not implemented yet. Still interested in this enhancement.

**Comment by swests** [comment]
Commenting to keep open

**Comment by nielsfaber** [comment]
I added this in v1.3.0.
The action buttons can now be resized independently from the keypad buttons.

Let me know if you're happy with the changes, you can close the request if so.

**Comment by swests** [comment]
Thanks Niels!  I will test this week and feedback.

**Comment by swests** [comment]
looks good.  Thanks!
