### ISSUE TITLE
Changing the button "Arm/Disarm" position?!

### ISSUE THREAD

**Issue by pickonedev** [nielsfaber/alarmo-card#24]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
[clear description of what you want to see changed or added]
There is any way to change the "ARM/DISARM" button position? 

### Additional info
[some example of how the new functionality should look like]
I would like to put the button "ARM/DISARM" to the left of button "0" (zero). In this way, I will have a more compact design

**Comment by nielsfaber** [comment]
I cannot satisfy this request since there are multiple arming actions possible:
<img src="https://user-images.githubusercontent.com/16861605/158655320-b3b8efe0-7266-47f2-97a1-b9820954458d.png" width="75%" height="75%">
They cannot be replaced by a single button.

**Comment by pickonedev** [comment]
It's ok... I managed to move the button through css. Thank you!

**Comment by pickonedev** [comment]
@nielsfaber At least, there is any way to change the "Code" text position to middle? The "Code" text inside the field where you add the code. It is strange to have the text in left, but the asterisks in the middle...

I tried with CSS but it is not working...

**Comment by nielsfaber** [comment]
@pickonedev As far as I know this is not possible.
The textfield which is used in the card is an element defined by HA, and uses the [mwc textfield](https://www.npmjs.com/package/@material/mwc-textfield) component.
I don't see any options to control the position of the placeholder text.
