### ISSUE TITLE
Circle around icon missing on iOS Safari / Companion app

### ISSUE THREAD

**Issue by ronaldheft** [nielsfaber/alarmo-card#27]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
A circle should appear around the Alarmo icon (which will also be used to indicate countdown status) in all browsers.

### Actual behavior
No circle is displayed around the icon, even when a countdown is active, on iOS in both Safari and the Companion app. The circle does appear on Safari on Mac. The latest iOS and Mac versions are in use.

![6DEFE45A-5507-4B2D-BE42-B13D12997FE0_1_201_a](https://user-images.githubusercontent.com/1143112/159193286-afadffdc-7505-4af6-91ab-8f2a23dd667c.jpeg)

### Steps to Reproduce
- Add the card to any lovelace view
- Open and view the card on iOS

**Comment by nielsfaber** [comment]
I'm seeing the same issue here, thanks for reporting.
Don't know what caused this to break (I didn't change anything related to it recently), but I will see what I can do..

**Comment by ronaldheft** [comment]
Still an issue.

**Comment by nielsfaber** [comment]
This should be fixed by updating the card to v1.4.0.
Please let me know if you still have issues after updating.
