### ISSUE TITLE
New menu for setting arming options not displaying properly in popup

### ISSUE THREAD

**Issue by h3nrytan** [nielsfaber/alarmo-card#28]
![image](https://user-images.githubusercontent.com/3590384/160047666-5e3fa2a3-7002-4189-a900-c3e53c07bed0.png)

With the latest update, the dropdown menu got cropped in popup. 
Also the dropdown menu closes the popup when clicking on other area.

i'm on 2022.3.7 with latest  alarmo card

**Comment by nielsfaber** [comment]
This does not happen for me. Can you tell me how I can reproduce this?

**Comment by h3nrytan** [comment]
i'm using custom component, browser_mod to create the popup
https://github.com/thomasloven/hass-browser_mod

you may recreate by the following:-

1. include the code below in script.yaml

#Security Alarm
  pop_up_security_alarm:
    alias: Pop Up Security Alarm
    sequence:
    - service: browser_mod.popup
      data: !include ../popup/security_alarm.yaml

2. in config create a folder popup and file name security_alarm.yaml

3. include the code below in security_alarm.yaml

  command: popup
  title: Home Security
  style:
    .: |
      :host .content {
        width: 100%;
        padding: 1.5em 1.5em 1.5em 1.5em;
      }
  card:
    type: custom:alarmo-card
    entity: alarm_control_panel.alarm

4. restart HA > go to developer tools > services > scripts: pop up security alarm > call service

5. you may view the issue.

**Comment by nielsfaber** [comment]
I cannot help you with that.
It seems this is an issue which only occurs in combination with the browser_mod plugin. I don’t guarantee compatibility with third party plugins (I don’t use this myself, so I don’t test for this).

**Comment by h3nrytan** [comment]
mini media player had similar issue. they have resolved. maybe it could be a reference for you:-

https://github.com/kalkih/mini-media-player/pull/635/commits/f1dc0bc130ada5cf45dbbd1f298fa0f3a4cbbb60

**Comment by h3nrytan** [comment]
> I cannot help you with that. It seems this is an issue which only occurs in combination with the browser_mod plugin. I don’t guarantee compatibility with third party plugins (I don’t use this myself, so I don’t test for this).

no problem. let me know if you require me to close this issue.
