### ISSUE TITLE
Icon state still blinking

### ISSUE THREAD

**Issue by yagrasdemonde** [nielsfaber/alarmo-card#31]
Hello,

It's seems there is a little bug with state icon.

Steps to reproduce :
Arm alarm, then a sensor is triggered, alarm is triggered. The state icon is blink red. Then after click to disarm, state icon return to green color but still blinking.

Demo on video below

https://user-images.githubusercontent.com/35835849/162820118-ff6312a5-38d8-4865-b6b4-d989e1631f98.mov

**Comment by nielsfaber** [comment]
For me the problem does not appear.
Can you provide more details such that I can reproduce this?
https://user-images.githubusercontent.com/16861605/166863250-8754c0c8-3d62-425b-b0b2-6662580f1f50.mov

**Comment by nielsfaber** [comment]
I could finally reproduce this in iOS / Safari. There's a fix on its way.

**Comment by nielsfaber** [comment]
This should be fixed by updating the card to v1.4.0.
Please let me know if you still have issues after updating.

**Comment by yagrasdemonde** [comment]
Sorry for long response.
Yes fix works. 
Thx
