### ISSUE TITLE
Keypad always visible

### ISSUE THREAD

**Issue by KameDomotics** [nielsfaber/alarmo-card#32]
Alarmo 1.8.7
Alarmo Card 1.3.0
Home Assistant 2022.4.5

Problem:
when the alarm is disarmed, the keypad is always visible.
I use a numeric code (4 digits) to activate the alarm system.

`
type: custom:alarmo-card
entity: alarm_control_panel.alarmo
keep_keypad_visible: false
button_scale_actions: 1
use_clear_icon: false
name: ALLARME
button_scale: 1
states:
  armed_away:
    hide: false
  disarmed:
    hide: false
button_scale_keypad: 1
show_messages: true
`

![E98F37F8-2F75-410C-B927-E314828C7955](https://user-images.githubusercontent.com/47695661/164313352-1a65d015-0e8c-4f54-b61f-22ec439a5bf1.png)

**Comment by nielsfaber** [comment]
This doesn’t seem like a bug to me.
If your setup requires a code for arming, keypad should be shown when alarm is disarmed, right?

**Comment by KameDomotics** [comment]
> This doesn’t seem like a bug to me.
> If your setup requires a code for arming, keypad should be shown when alarm is disarmed, right?

Exactly, but isn't there a way to show the keyboard only when needed?
Example:
Press "Arming home" -> keyboard appears -> code entry -> system armed.

This is to have a more compact and easier card.
It might be an idea, first you hit the action button and then the code.
Thanks
