### ISSUE TITLE
Countdown not shown

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo-card#36]
Since Alarmo release 1.9.1 the countdown isn't shown anymore.
Neither Alarmo-Card version 1.4.0, nor 1.3.0 do.
I suppose, those try to get the countdown time from websockets.

**Comment by nielsfaber** [comment]
Release 1.4.0 should do this. 1.3.0 doesn’t work fine with Alarmo 1.9.x.
Please stick to 1.4.0, check your browser cache if the version is displayed correctly (maybe the old one is kept in cache?)

If things don’t work OK still I would need some details:
- exit or entry delay not working?
- is it a normal alarm entity or the master alarm (if you have multiple areas)?

**Comment by Eyco1981** [comment]
Version 1.4.0 isn't available anymore on HACS. Github shows 1.3.0 as current release. 
Exit and entry delays are working fine. But 1.4.0 didn't show the countdown. I'm using the master entity containing one zone with and one without exit delay.

**Comment by Eyco1981** [comment]
I have tried it with 2 independent HA installations and with 2 browsers (both with clearing cache) - same result.

**Comment by Eyco1981** [comment]
Did some testing with Alarmo 1.9.1 and Alarmo-Card 1.4.0. Alarm cards for zones with or without delay work as expected. Just the Master does not show the countdown - even when all zones are with same delay.
![alarmo](https://user-images.githubusercontent.com/88980079/167264102-228422df-eeb0-4c83-bcef-0ddb0ab12f6f.png)

**Comment by nielsfaber** [comment]
Thanks for taking the effort of investigating the scenario where the issue occurs, it is really half the work.
You're probably right and this is an issue for master only, I will take a look at the code when I can.

> Version 1.4.0 isn't available anymore on HACS. Github shows 1.3.0 as current release.

This should be solved. I don't know what causes it but I had to re-make the release.

**Comment by nielsfaber** [comment]
Please try updating to v1.9.2. I indeed found a (quite serious) bug here, and could reproduce and solve your issue.

**Comment by Eyco1981** [comment]
Can confirm Master countdown is working now.
Thank you very much for fixing!
