### ISSUE TITLE
No support prior IOS 11.1

### ISSUE THREAD

**Issue by mattexpa** [nielsfaber/alarmo-card#4]
On IOS devices running IOS lower than 11.1 HASS isn't able to display the custom element card.
### Checklist
- [ x ] I checked for similar existing issues (both open and closed) before posting.
- [ x ] I am running the latest version.

### Expected behavior
Display the card normally just like any other native cards.

### Actual behavior
Red box is being displayed stating that the custom element doesn't exist.

### Steps to Reproduce
Try to access the card on a IOS device running IOS <11.1

Tried to fix it myself and found this post in a similar Issue report (might be the solution as far as i can tell?)
https://github.com/gurbyz/power-wheel-card/issues/11#issuecomment-472014247

**Comment by nielsfaber** [comment]
I don't know  how to help with this.
iOS10 is pretty much obsolete, i don't have any devices around to test it.
The power-wheel-card does not use typescript and/or rollup so I couldn't get any clues from there.
