### ISSUE TITLE
Alarmo-Card cannot establish connection

### ISSUE THREAD

**Issue by ghxstxch** [nielsfaber/alarmo-card#42]
### Checklist
- [x ] I checked for similar existing issues (both open and closed) before posting. (Similar to staled Issue #30 )
- [ x] I am running the latest version.

### Expected behavior
The alarmo-card to function

### Actual behavior
Card outputs "Could not establish a connection with the alarmo integration. Please check if it is installed and the correct entity is selected in the card settings." Triple checked over and the correct entity is being used, and the alarmo integration is indeed installed.

### Steps to Reproduce
Issue occurs both using the HACS add-on to install and the manual method. Both create the same exact issue.

**Comment by ghxstxch** [comment]
-Alarmo is running
-Logs mention alarmo here: `2022-06-13 21:07:52 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for alarmo using this method at custom_components/alarmo/__init__.py, line 49: device_registry = await dr.async_get_registry(hass)`

-Nothing fishy in browser logs it seems

**Comment by ilgio** [comment]
I have same problem

**Comment by nielsfaber** [comment]
@Spross1 Any idea how I could reproduce this in my own setup? For me alarmo-card starts up fine 10/10 times. I wouldn't know how to improve things if I cannot test the problem myself.

**Comment by Spross1** [comment]
I don't think it's your fault. I'm only experiencing this issue with my wall-mounted tablets and as you've mentioned before that is a WebSocket issue I believe as those are the first 3 logs that pop up and I have 3 wall-mounted tablets. I followed another thread that will give me a "home assistant started" event in node-red, and I'll use this event to trigger a refresh of the page on my 3 tablets. So even though this wasn't a big deal for me to begin with, this solution will make all of my tablets fix their own issue. Thanks again for your work, I love both Alarmo and this card. For the others with this "issue", this discussion has a few solutions if you're not a node-red user. [Node-RED, trigger sequence on HA Start](https://community.home-assistant.io/t/node-red-trigger-sequence-on-ha-start/55080)]
