### ISSUE TITLE
Arm-Icons instead of Text

### ISSUE THREAD

**Issue by snickers2k** [nielsfaber/alarmo-card#47]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
would love to have an option for **icons for arming, instead of text**

**Comment by nielsfaber** [comment]
This has been discussed in https://github.com/nielsfaber/alarmo-card/issues/10
I made an attempt to implement this but didn't like it much, hence it was never released.
Do you like the example which was shown there? 
Else, how would you like to display it (preferably in the same style as other buttons that can be found in HA)?

**Comment by snickers2k** [comment]
i like the example. would be really happy with it.

**Comment by MarcelS1988** [comment]
What is the status, I like also the Icon instead of the text, so please make it actual, I don't see this yet?
