### ISSUE TITLE
Can not add an entity in the alarmo-card

### ISSUE THREAD

**Issue by HabelStefan** [nielsfaber/alarmo-card#48]
I can not use the alarmocard.

I always get

" Invalid configuration provided for entity error.
type: custom:alarmo-card"

### Checklist
- [ ] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version, both alarmo-card and home-assistant (2022.11)

### Expected behavior
Be able to add an entity when adding a card.

### Actual behavior
Field to add does not appear

See the attached screenshot.
<img width="1488" alt="screenshot" src="https://user-images.githubusercontent.com/24601959/205917985-dda1032d-afd6-4b82-bd61-07fef054151a.png">

**Comment by nielsfaber** [comment]
Could you please check the version of alarmo card which is running?
It's displayed in the console:
<img src="https://user-images.githubusercontent.com/16861605/205919406-d3c36c50-9e17-45da-8323-39ffb18114a7.png" width="75%" height="75%">

**Comment by HabelStefan** [comment]
Its 1.4.1, installed it this morning through HACS..

**Comment by nielsfaber** [comment]
Can you check what the console log states anyway?
There may be an older version stored in your browser cache.

**Comment by HabelStefan** [comment]
Same result. I cleared the browser cache before. Same result using chrome.

<img width="463" alt="Bildschirm­foto 2022-12-06 um 14 11 50" src="https://user-images.githubusercontent.com/24601959/205921684-892ba5dc-f2ed-483e-a2d9-69d6eb56e65e.png">

**Comment by nielsfaber** [comment]
Hmm, I'm not sure what's the matter. I'm on the same HA version and no problems here.
The error message suggests there could be a problem with the connection to Alarmo.
I assume you do have Alarmo running (and without problems)?

**Comment by HabelStefan** [comment]
Hmm,

i did not change anything, not even restart Cassio / my Mac, but now it works :)
