### ISSUE TITLE
Alarmo under RTL Languages

### ISSUE THREAD

**Issue by niraviry** [nielsfaber/alarmo-card#54]
### Alarmo Version

v1.9.7

### HA Version

2023.1.2

### Bug description

The Alarmo card has a bug when working with RTL (Hebrew in my case). 
1. The Entity field does not show. Moving to English shows it and enables defining it. Moving back to Hebrew and I guess any other RTL Language keeps the Entity field in place.
2. The pin field is set to the right hand side and not placed in the middle.
3. On some of the setup pages (actions for instance) menus are not aligned properly and are one over the other.
4. I did try to add the entity entry in the code editor but it did not work. This needs double verification but if nielsfaber/alarmo#1 is fixed, this will not be an issue anymore.

### Steps to reproduce

Just add an new Alarmo Card under to the dashboard while under Hebrew and I guess Arabic.

### Relevant log output

```shell
No need
```

**Comment by nielsfaber** [comment]
I'm sorry but I did not spend any effort making the card compatible with RTL mode (the same applies to the configuration GUI of alarmo).
For me it is rather hard to test, because I don't know how things are supposed to look in Hebrew.

**Comment by niraviry** [comment]
The basic problems are not related to RTL itself and the way it supposed to look.
If you simply change to Hebrew, the Entity field disappears so you get an error.
Trying to set various parameters, the parameters fields are still in English but the labels are messed up overlapping each other.
If you like, I can help translating to Hebrew.

**Comment by niraviry** [comment]
I can say that it is quite impossible to work under RTL languages in the Alalrmo. All menus are remain in English but it is a mess when it comes to the UI.
Furthermore, I have discovered another bug. I set an action - Pushover Notification for Alarm arm - Home.
I reports Away instead of Home.

**Comment by niraviry** [comment]
I got a strange situation. Everything is working fine yet or even great but under HACS the Alarmo card is reported as not loaded properly to Lovelace. No other report.
