### ISSUE TITLE
Is there a way to go from mode to mode bypassing the need to disarm first?

### ISSUE THREAD

**Issue by stevenhung909** [nielsfaber/alarmo-card#58]
Is there a way to go from mode to mode bypassing the need to disarm first? 
this feature would be useful to prevent unnecessary mode changes

Thank you

**Comment by nielsfaber** [comment]
Currently this is not possible.
However, alarmo itself does support this.
How would you suggest to have this function integrated in the card?
I am wondering how to do so without introducing clutter.
