### ISSUE TITLE
States not shown

### ISSUE THREAD

**Issue by Eyco1981** [nielsfaber/alarmo-card#59]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
State of the Alarmo entity shown in card.
(State label)

### Actual behavior
No state shown in card (except the icon) since HA Core 2023.4.4.
Cause might be the new translation change in Home Assistant.

### Steps to Reproduce
- Arm/disarm Alarmo entity

**Comment by amadorpozo** [comment]
Same issue in here. I have the card in Spanish.

**Comment by nielsfaber** [comment]
This should be resolved by updating alarmo-card to v1.5.0.
@Eyco1981 Could you please update the card and confirm it works OK now?
You can close the issue if this is the case.
