### ISSUE TITLE
Alarmo Card Problem - Not Supported Error

### ISSUE THREAD

**Issue by clipse2004** [nielsfaber/alarmo-card#6]
hi Dude, 

since the latest Homeassistant Update I got this error sometimes:
ERROR (MainThread) [frontend.js.latest.202108090] https://xxxxx.duckdns.org/hacsfiles/alarmo-card/alarmo-card.js:162:73 NotSupportedError: Cannot define multiple custom elements with the same tag name

Don't know why because I don't have multiple custom elements from Alarmo

big thx for your help

**Comment by nielsfaber** [comment]
This should be solved by updating to latest version of alarmo.

**Comment by clipse2004** [comment]
Yep sorry i forgot to close ;)
Thx
