### ISSUE TITLE
Changing Mode Names on Alarmo Card Freezes Web Browser

### ISSUE THREAD

**Issue by sammyh2506** [nielsfaber/alarmo-card#60]
### Alarmo Version

v1.9.8

### HA Version

2023.4.0

### Bug description

I can edit all the fields on the Alarmo card but when I attempt to change the name of the modes the web page freezes as soon as I click the edit icon.  

### Steps to reproduce

Editing the Alarmo card on any of my Dashboards produces the same issue.

**Comment by nielsfaber** [comment]
This should be resolved by updating alarmo-card to v1.5.0.
@sammyh2506 Could you please update the card and confirm it works OK now?
You can close the issue if this is the case.

**Comment by sammyh2506** [comment]
All good on V.1.5.0.

Thank you and continue the great work on Alarmo.
