### ISSUE TITLE
State badge color

### ISSUE THREAD

**Issue by KameDomotics** [nielsfaber/alarmo-card#63]
Hi, I would like to propose this new feature.

- Customize the color of the status badge
- Armed: GREEN (now)
- Disarmed: GRAY (now)

Actually you can customize the text and other parameters, but not the color of the status badge.

I didn't find the way to change these badge colors in the theme .yaml file (Google Dark Theme).

![IMG_4505](https://github.com/nielsfaber/alarmo-card/assets/47695661/2bc49264-3707-47ef-9943-3e2338289070)

**Comment by nielsfaber** [comment]
See #53
