### ISSUE TITLE
[FR] Show bypassed sensors in armed mode

### ISSUE THREAD

**Issue by erkr** [nielsfaber/alarmo-card#76]
When I choose the panel option to `bypass open sensors`, when arming the alarm, there is no feedback that these sensors are bypassed (or still bypassed after re-activated when closed after arming).

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Please make the icon orange as long the sensors are bypassed and ( offer an option to) show the bypassed sensors.

### Additional info
[some example of how the new functionality should look like]

**Comment by erkr** [comment]
Bump, unless author doesn't like it, I would be happy to have it 😀

**Comment by nielsfaber** [comment]
I added this feature in the latest update of the card. Hope it satisfies your needs.

**Comment by erkr** [comment]
Wauw, doesn't see that yet 👍

**Comment by erkr** [comment]
I'm very 😃 
![image](https://github.com/nielsfaber/alarmo-card/assets/4363599/d0099ddf-77e9-4760-ac90-af16cc87f6a7)
Will close this FR. Thanks!
