### ISSUE TITLE
Could not establish a connection with the alarmo integration

### ISSUE THREAD

**Issue by bcutter** [nielsfaber/alarmo-card#84]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
Card is shown, also with former Alarmo integration versions

### Actual behavior
![grafik](https://github.com/nielsfaber/alarmo-card/assets/13799156/bd4fe937-e61e-4eac-93ff-d8770dcd5b3e)

### Steps to Reproduce
Use HA 2023.4.x with Alarmo integration v1.9.13 (last one, see https://github.com/nielsfaber/alarmo/issues/891) and Alarmo card v1.5.2 or even previous v1.5.1.

I don't know when/what broke it in the last weeks (downgraded to v1.5.1 which did not fix it) and yes, HA Core needs an update.

**Comment by bmangodt** [comment]
Same issue here with Alarmo card v1.5.2, Alarmo v1.9.15 and HA Core 2024.4.2

**Comment by bcutter** [comment]
Not stale

**Comment by nielsfaber** [comment]
Could you place update HA and alarmo to latest version and retry?

**Comment by bcutter** [comment]
No. HA is on 2023.9 currently and it will take some more time to update to latest version.

I see hacs.json (still) does not contain a minimum required HA version. Are you aware of the dependencies? What HA version has been tested with this integration?

**Comment by bmangodt** [comment]
Can confirm it works now with Alarmo v1.10.4 and Alarmo Card v1.5.2. My HA version is 2024.7.3, but the issue was only fixed with the Alarmo v1.10 update so I don't think updating HA is going to be necessary @bcutter

**Comment by bcutter** [comment]
> but the issue was only fixed with the Alarmo v1.10 update so I don't think updating HA is going to be necessary

Well, it certainly is: because https://github.com/nielsfaber/alarmo/blob/main/hacs.json states it requires HA version 2024.7.0 at minimum.

**Comment by bcutter** [comment]
Please note: HA 2024.1.6 with Alarmo 1.9.14 and Alarmo Card 1.5.2 still gives a non-functional state (nothing in HA log, but the GUI is not working...)

![grafik](https://github.com/user-attachments/assets/4165121d-c636-45ab-951a-1bed32718874)

**Seems to be almost impossible to find the right set of versions (HA, alarmo, alarmo-card) to finally have a working setup.**
I know no other integration (feature or UI) depending so strongly on every single HA release.

I have no idea how to finally find a working setup (next to just updating all 3 components to their latest versions, which simply takes quite some time - and Alarmo is not the first priority tbh).

**Comment by nielsfaber** [comment]
@bcutter I am closing this issue since I only provide support for latest versions, Since you're not willing to upgrade, I cannot help you.
