### ISSUE TITLE
Alarmo installed not work

### ISSUE THREAD

**Issue by Nexow91** [nielsfaber/alarmo-card#88]
hello first of all, thank you very much for such a loveace. 
Unfortunately it doesn't work for me i have installed the loveace via hacs and can also find it under the maps unfortunately only the round circle turns here all the time. Simply entering the code into the card via yaml results in it not being able to find the entity. 

What I have tried so far. 
Reinstall via HACS, system reboot (+ Homeassistant) 

but still the same problem. 
I have also installed other loveaces via hacs but they work. 

Here are a few key data about my system

Proxmox 
HA (VM) 

Homeassistant
Core 2024.5.5
Frontend 20240501.1

Maybe go to the latest Core ? 
2024.6.3

Thanks for any advice. 

![image](https://github.com/nielsfaber/alarmo-card/assets/73191540/cd167878-f405-40f3-9150-70fcbc0267b2)
![image](https://github.com/nielsfaber/alarmo-card/assets/73191540/fd95a9c2-0d98-477d-b3ff-4f3f5f3e9710)
![image](https://github.com/nielsfaber/alarmo-card/assets/73191540/9ab8d11c-b214-47a7-8ceb-ed40ded8376b)
![image](https://github.com/nielsfaber/alarmo-card/assets/73191540/13f5328a-5f19-4e21-a65f-7dafe2e7c352)

**Comment by EnricoBettella** [comment]
I don't actually know if it's the same problem, but for me Alarmo Card is not working anymore because it cannot establish the connection with Alarmo. 
![Screenshot 2024-07-04 alle 19 04 24](https://github.com/nielsfaber/alarmo-card/assets/61935282/a3b3a0d2-a917-4c1f-9432-668c5747c359)

**Comment by nielsfaber** [comment]
@Nexow91 The card is telling you that the `alarm_control_panel.alarmo` entity doesn't exist. This is not a bug, you should just edit the card configuration and set the correct entity.

@EnricoBettella This seems a different issue indeed. Did you check the integration is working OK? Perhaps emptying the browser cache may help.

**Comment by bcutter** [comment]
> I don't actually know if it's the same problem, but for me Alarmo Card is not working anymore because it cannot establish the connection with Alarmo. 
> 
> ![Screenshot 2024-07-04 alle 19 04 24](https://github.com/nielsfaber/alarmo-card/assets/61935282/a3b3a0d2-a917-4c1f-9432-668c5747c359)
> 
> 

See https://github.com/nielsfaber/alarmo-card/issues/84 for this issue.

Unfortunately the maintainer decided to close (and rudely lock) it before I could manage to update everything around Alarmo to the latest version (updating HA takes some time when you have to catch up quite some months) to confirm the issue is actually fixed.

I'd recommend to follow his instructions and update HA, Alarmo integration and Alarmo-Card integration to the very latest version. Seems like HA Core changes that much under the hood on almost every release (monthly) that Alarmo or Alarmo-Card breaks.

**Comment by EnricoBettella** [comment]
@bcutter
That is actually the same issue I’m facing! Strange I didn’t see that issue open😅, thank you!
Since I usually keep HA updated to the last few months, I’m going to update everything since it seems to fix it.
