### ISSUE TITLE
Skip delay and Force

### ISSUE THREAD

**Issue by rindlerblabla** [nielsfaber/alarmo-card#9]
First, thanks a lot for developing Alarmo! Really appreciate it!

When I am arming from the alarmo card I am always away from home, which makes the delay unnecessary and just an extra period of waiting until the arming is confirmed.

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I think it would be nice to be able to skip the delay and force bypassing of the open sensors when arming from the card, similar to the options available when arming from an automation.

### Additional info
Would be enough with tick boxes when you edit the display of a certain arming mode.

**Comment by nielsfaber** [comment]
I agree this is a good next step 👍 
Not sure if it should be just a checkbox or something else like a toggle button or something  🤔

**Comment by rindlerblabla** [comment]
Not implemented yet.

**Comment by rindlerblabla** [comment]
Am still interested in this feature.

**Comment by rindlerblabla** [comment]
Am still interested in this feature.

**Comment by rindlerblabla** [comment]
Am still interested in this feature.

**Comment by nielsfaber** [comment]
Thank you for your patience 👍 

I added a menu in the corner where you can set these options:
<img src="https://user-images.githubusercontent.com/16861605/159112553-124e33e8-cd9e-446d-9906-1149aebcb43c.png" width="75%" height="75%">

Let me know if you're happy with this change.
If all is OK, you can close the request.

**Comment by rindlerblabla** [comment]
Thanks! Seems like a good solution!

**Comment by rindlerblabla** [comment]
Did some updates to HA and now it's working just fine! Thanks a lot!
